# Generated by Django 5.2.6 on 2025-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_year', models.IntegerField()),
                ('movie_language', models.CharField(default='None', max_length=20)),
                ('movie_genre', models.CharField(default='None', max_length=20)),
                ('movie_director', models.CharField(max_length=20)),
                ('movie_description', models.TextField()),
                ('movie_image', models.ImageField(upload_to='movie_images')),
            ],
        ),
        migrations.CreateModel(
            name='MovieWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_year', models.IntegerField()),
                ('movie_genre', models.CharField(max_length=20)),
                ('movie_image', models.ImageField(upload_to='movie_watchlist')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=20)),
                ('series_year', models.CharField(max_length=10)),
                ('series_language', models.CharField(default='None', max_length=10)),
                ('series_genre', models.CharField(default='None', max_length=20)),
                ('series_seasons', models.CharField(max_length=20)),
                ('series_director', models.CharField(max_length=20)),
                ('series_description', models.TextField()),
                ('series_image', models.ImageField(upload_to='series_images')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=20)),
                ('series_year', models.CharField(max_length=10)),
                ('series_genre', models.CharField(max_length=20)),
                ('series_seasons', models.CharField(max_length=20)),
                ('series_image', models.ImageField(upload_to='series_watchlist')),
            ],
        ),
    ]
