# Generated by Django 5.2.6 on 2025-10-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_year', models.IntegerField()),
                ('movie_director', models.CharField(max_length=50)),
                ('movie_descrption', models.TextField()),
                ('movie_image', models.ImageField(upload_to='movie_images')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50)),
                ('series_year', models.CharField(max_length=50)),
                ('series_seasons', models.IntegerField()),
                ('series_director', models.CharField(max_length=50)),
                ('series_descrption', models.TextField()),
                ('series_image', models.ImageField(upload_to='series_images')),
            ],
        ),
    ]
