# Generated by Django 5.2.6 on 2025-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_director',
            field=models.CharField(max_length=50),
        ),
    ]
