# Generated by Django 5.2.7 on 2025-10-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='series_genre',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_director',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_language',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_seasons',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_year',
            field=models.CharField(max_length=10),
        ),
    ]
