# Generated by Django 5.2.6 on 2025-10-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='series',
            name='series_language',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
