# Generated by Django 5.2.6 on 2025-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=50),
        ),
    ]
