# Generated by Django 5.2.7 on 2025-10-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_movie_genre_series_series_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=20)),
                ('series_year', models.CharField(max_length=10)),
                ('series_genre', models.CharField(max_length=20)),
                ('series_seasons', models.CharField(max_length=20)),
                ('series_image', models.ImageField(upload_to='series_watchlist')),
            ],
        ),
    ]
