# Generated by Django 5.2.6 on 2025-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movie_movie_genre_alter_movie_movie_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_director',
            field=models.CharField(max_length=100),
        ),
    ]
