# Generated by Django 5.2.7 on 2025-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_serieswatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_year', models.IntegerField()),
                ('movie_genre', models.CharField(max_length=20)),
                ('movie_image', models.ImageField(upload_to='movie_watchlist')),
            ],
        ),
    ]
