# Generated by Django 5.2.7 on 2025-10-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_moviewatchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_descrption',
            new_name='movie_description',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_descrption',
            new_name='series_description',
        ),
    ]
